---
- name: Single node Kubernetes
  hosts: single
  gather_facts: True
  become: True
  vars:
    hostname: k8s
    metallb_enabled: true
    istio_enabled: true
    cert_manager_enabled: true
    github_actions_controller_enabled: true
    argocd_enabled: true
    vault_addr: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR') }}"
    vault_token: "{{ lookup('ansible.builtin.env', 'VAULT_TOKEN') }}"
    

  roles:
    - role: common

    - role: kubernetes
      vars:
        kubernetes_fqdn: kubernetes.teokyllc.internal
        kubernetes_pod_cidr: 10.244.0.0/16

    - role: metallb
      when: metallb_enabled
      vars:
        metallb_namespace: metallb-system
        metallb_ip_range: 192.168.1.240-192.168.1.250

    - role: istio
      when: istio_enabled
      vars:
        istio_version: 1.15.3
        istio_sample_app_enabled: true
        istio_sample_app_namespace: bookinfo

    - role: cert-manager
      when: cert_manager_enabled
      vars:
        cert_manager_namespace: cert-manager
        vault_issuer_enabled: true
        vault_signing_path: pki/sign/intermediate-teokyllc-internal

    - role: actions-runner-controller
      when: github_actions_controller_enabled
      vars:
        github_org: teokyllc
        actions_runner_controller_namespace: actions-runner-system
        actions_runner_namespace: actions-runner
        actions_runner_repository: cr.teokyllc.internal
        actions_runner_image: actions-runner-dind
        actions_runner_tag: latest
        actions_runner_replicas: 1

    - role: argocd
      when: argocd_enabled
      vars:
        argo_cd_namespace: argo-cd
        argo_cd_fqdn: argocd.teokyllc.internal
        redis_ha: false
        controller_replicas: 1
        repo_server_replicas: 1
        application_set_replicas: 1
        enable_istio_routing: true
