---
- hosts: 192.168.1.5
  gather_facts: True
  become: True
  tasks:

    - name: Apt update packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install packages
      ansible.builtin.apt:
        pkg:
        - apt-transport-https
        - containerd
        - curl

    - name: Copy kernel modules
      ansible.builtin.copy:
        src: files/k8s-modules.conf
        dest: /etc/modules-load.d/k8s-modules.conf

    - name: Copy kernel parameters
      ansible.builtin.copy:
        src: files/k8s-kernel-params.conf
        dest: /etc/sysctl.d/k8s.conf

    - name: Reload sysctl
      ansible.builtin.shell: |
        sysctl --system

    - name: Deploy Flannel CNI
      ansible.builtin.shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
        kubectl taint node k8s node-role.kubernetes.io/control-plane:NoSchedule-

    - name: Create containerd config
      ansible.builtin.shell: |
        mkdir -p /etc/containerd
        containerd config default | tee /etc/containerd/config.toml 
        sed -i "s/SystemdCgroup = false/SystemdCgroup = true/g" /etc/containerd/config.toml

    - name: Restart containerd
      ansible.builtin.systemd:
        state: restarted
        name: containerd
        enabled: yes

    - name: Install Kubernetes bins
      ansible.builtin.shell: |
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add
        apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"
        apt install -y kubeadm kubelet kubectl
        apt-mark hold kubelet kubeadm kubectl

    - name: Check if kubeadm init has been run
      stat:
        path: /root/k8s-init
      register: kubeadm_init_result

    - name: Deploy Kubernetes
      ansible.builtin.shell: |
        kubeadm init --pod-network-cidr=10.244.0.0/16 --control-plane-endpoint=kubernetes.teokyllc.internal > /root/k8s-init
      when: not skubeadm_init_result.stat.exists

    - name: Deploy Flannel CNI
      ansible.builtin.shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
        kubectl taint node k8s node-role.kubernetes.io/control-plane:NoSchedule-

    - name: Untaint master node
      ansible.builtin.shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        kubectl taint node k8s node-role.kubernetes.io/control-plane:NoSchedule-